### ISSUE TITLE
x.keyboardActor is null {Fixed/Update!}

### ISSUE THREAD

**Issue by d34dh0r53** [ckissane/blur-me#10]
Fedora Rawhide, Gnome 40

Error: x.keyboardActor is null trying to enable the extension.  Let me know what package versions you need and I'll provide them along with any logs you'd like.

**Comment by ckissane** [comment]
For those getting an error on the latest update, a temporary fix is to enable the onscreen keyboard in accessibility settings until the next update that fixes this is approved.
