### ISSUE TITLE
License to GPL

### ISSUE THREAD

**Issue by aunetx** [ckissane/blur-me#15]
Hi, I am the maintainer of Blur my Shell (from which you forked), and glad of all your work here.

I really hope applications blur will be added in Blur my Shell too, and was wondering btw if it caused you any problem to look at your code when I (or @CorvetteCole maybe) implement applications blur?
I would understand if you prefer to keep the implementation for your extension by the way, I mean just asking in case I would need it (so I would not feel ashamed by copying part of your work if you say yes).

The real issue is that the license used here is not the right one (and totally my fault), I licensed the project under GPL at the beginning (as seen in readme), but later was silly and added MIT license file to the project.
The problem is that extensions.gnome.org accepts only GPL extensions, so you might want to change the license file in your fork too.

Sorry for the long issue, and good chance for this extension :)

**Comment by ckissane** [comment]
Totally should be GPL and now with your permission, we can do that I guess!

**Comment by ckissane** [comment]
GPL 3?

**Comment by ckissane** [comment]
@aunetx also I think application blur is pretty complete now that you can exclude applications by process name

**Comment by ckissane** [comment]
@aunetx done

**Comment by CorvetteCole** [comment]
@ckissane your work here is great, but kind of the opposite of the original goal of blur-provider (provide blur to applications that ask for it, and then to applications the user specifically selects vs all applications by default). I think at some point we will have an option for blurring everything but that is not the plan for now (in case you were curious)

**Comment by ckissane** [comment]
@CorvetteCole I have per application toggle
