### ISSUE TITLE
Optional "Toggle Application Blur" visibility in topbar.

### ISSUE THREAD

**Issue by grigio** [ckissane/blur-me#17]
Great extension! Can you replace the name in the topbar with an icor or emoji ?

I propose to rename "Toggle Application Blur" with "🎚"

**Comment by ckissane** [comment]
good idea!

**Comment by eh8** [comment]
Could this be an optional UI element? It occupies a large amount of top bar space.

**Comment by AdsonCicilioti** [comment]
Nooooo!  Make it optional on Blur Me Settings... Please!!

**Comment by grigio** [comment]
Yeah probably the best way to deal with it is to have toggle button in the extension configuration to enable and disable the "configuration mode"

**Comment by difrkaguilar** [comment]
Even if the extension don´t give us a hide settings form top bar option. This is another option to make the extension more integrated with gnome.

![Screenshot-20210517174133-3840x2160](https://user-images.githubusercontent.com/67672868/118563892-5ca2e700-b73d-11eb-800d-4ee2dcd8216c.png)

**Comment by ckissane** [comment]
Due to the limitations of where I can fetch the list applications from (There is no api to fetch it that can be called from the regular extension preferences), I do need to have this menu somewhere.

I am open to suggestions of where else it can be put, perhaps next to the wifi indicators etc.

PRs are also welcome

**Comment by difrkaguilar** [comment]
A little and unintrusive icon at the top bar can be the solution. I made a mockup using an icon of the Bootstrap Icon Set (https://icons.getbootstrap.com/)

![Screenshot-20210723172654-1149x39](https://user-images.githubusercontent.com/67672868/126844641-e2689b94-308d-40a3-9932-f33233ebf73e.png)

I don´t know if you can put in other part like the shell menu.

![Screenshot-20210723172056-359x783](https://user-images.githubusercontent.com/67672868/126844348-e2f1014f-697b-4285-a5ba-fcbf330ac0d2.png)
