### ISSUE TITLE
[Feature Request] Make the "Toggle Application Blur" button optional

### ISSUE THREAD

**Issue by daniel071** [ckissane/blur-me#18]
While this is a useful feature for a lot of people, I'd prefer to have my top bar more minimal with only the things I need to use. It should be possible to toggle this button on/off.
![image](https://user-images.githubusercontent.com/45705145/118227318-ae443b00-b4cb-11eb-8c79-f8caa575d03a.png)

Perhaps add an option in the settings menu, in the "Exclude Applications" section, named "Show application blur menu in top bar"
![image](https://user-images.githubusercontent.com/45705145/118227575-1c88fd80-b4cc-11eb-917a-21ffa47a9e5e.png)

**Comment by AdsonCicilioti** [comment]
Please!!  This arbritrary button is horrible!! ...And kill the Gnome approach Design.
Please make this optional!

**Comment by ckissane** [comment]
Will do!

**Comment by Willdrick** [comment]
Any news on this? I was thinking it'd be nicer to have the "Toggle Application Blur" button as a teardrop icon (blur icon on most graphics programs) on the right where systray an other extension icons normally live

![image](https://user-images.githubusercontent.com/2455158/126874268-631b15d2-5614-4c1c-8a84-833c08544f8c.png)

**Comment by ckissane** [comment]
I would like that as well, but I am not sure how to put it there? A pull request would be welcome

**Comment by daniel071** [comment]
Seeing that no-one was working on adding this, I implemented it myself. You can see it here: #34 

If you want to get the feature early before it gets merged, run this in your terminal:
```bash
git clone https://github.com/daniel071/blur-me.git
cd blur-me
make ; make install
```

I'll close the issue once the PR gets merged

**Comment by ckissane** [comment]
Merged
