### ISSUE TITLE
not working on ubuntu 21.04 wayland gnome 3.38 

### ISSUE THREAD

**Issue by anishkumar127** [ckissane/blur-me#20]
its showing this error 
TypeError: this._sigma_scale is null

Stack trace:
  _init@/home/anish/.local/share/gnome-shell/extensions/blur-me@nunchucks/prefs.js:35:7
  buildPrefsWidget@/home/anish/.local/share/gnome-shell/extensions/blur-me@nunchucks/prefs.js:157:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
// screenshot -
 <a href="https://ibb.co/Wncg3JW"><img src="https://i.ibb.co/Wncg3JW/Screenshot-from-2021-05-20-15-21-21.png" alt="Screenshot-from-2021-05-20-15-21-21" border="0"></a> <a href="https://ibb.co/x3yjCTd"><img src="https://i.ibb.co/x3yjCTd/Screenshot-from-2021-05-20-15-21-12.png" alt="Screenshot-from-2021-05-20-15-21-12" border="0"></a>

**Comment by ckissane** [comment]
The extension requires gnome 40

**Comment by anishkumar127** [comment]
how can i run in gnome 3.38 ?

**Comment by nlagunaq** [comment]
It doesn´t work with gnome 40.1. Same error.

![version](https://user-images.githubusercontent.com/84794983/119534270-566bc680-bd4c-11eb-9d14-031f2f703d8c.png)
![error](https://user-images.githubusercontent.com/84794983/119534714-d3973b80-bd4c-11eb-94d8-04b8ad2923b7.png)

**Comment by ckissane** [comment]
Closing in favor of https://github.com/ckissane/blur-me/issues/30
