### ISSUE TITLE
Prefs not working on gnome 40.1

### ISSUE THREAD

**Issue by nlaq** [ckissane/blur-me#21]
Preferences  won´t work with gnome 40.1.

![error](https://user-images.githubusercontent.com/84794983/119535109-4dc7c000-bd4d-11eb-8f78-238fb3fb30d6.png)
![version](https://user-images.githubusercontent.com/84794983/119535111-4e605680-bd4d-11eb-8f51-870da6f393ed.png)

**Comment by ckissane** [comment]
@nlaq Will look into

**Comment by ckissane** [comment]
Closing in favor of https://github.com/ckissane/blur-me/issues/30
