### ISSUE TITLE
Hey, got an error upon opening the settings via gnome-tweaks

### ISSUE THREAD

**Issue by AnishDe12020** [ckissane/blur-me#27]
Just installed the extension and tried opening the settings menu via gnome-tweaks extensions tab and i found this error: 
![image](https://user-images.githubusercontent.com/63192115/124757445-37677380-df4b-11eb-9663-cfaefa7000e4.png)
Hope it gets fixed!!!

**Comment by ckissane** [comment]
gnome version?

**Comment by AnishDe12020** [comment]
Gnome 3.38.5
Pop OS 21.04

**Comment by ckissane** [comment]
@AnishDe12020 this extension only supports Gnome 40 +, could you try updating?

**Comment by ckissane** [comment]
Closing in favor of https://github.com/ckissane/blur-me/issues/30
