### ISSUE TITLE
Entry in GNOME Extensions broken

### ISSUE THREAD

**Issue by eh8** [ckissane/blur-me#4]
![image](https://user-images.githubusercontent.com/22990581/116842940-555fd300-abac-11eb-8cdb-49fd0e562da9.png)

![image](https://user-images.githubusercontent.com/22990581/116842968-6b6d9380-abac-11eb-893e-8cbc82861c23.png)

[From the most recent commit](https://aur.archlinux.org/packages/gnome-shell-extension-blur-me-git/)

**Comment by dudumartins** [comment]
Same here... Im using Arch Gnome 40

**Comment by bmarien** [comment]
Exactly the same. On arch X11

**Comment by ckissane** [comment]
This is because of the keyboard issue, I have pushed a fix but It needs to be reviewed, until then enable onscreen keyboard in accessibility.

**Comment by ckissane** [comment]
Fixed
