### ISSUE TITLE
Gnome 41 support?

### ISSUE THREAD

**Issue by MRSS02** [ckissane/blur-me#41]
Does it support GNOME 41?

**Comment by rexmtorres** [comment]
Please add support for GNOME 41.  Please...

**Comment by ckissane** [comment]
@rexmtorres @MRSS02 I'll try to do this over thanksgiving break (college has been taking up a lot of my time)

**Comment by Neo-29** [comment]
Hello.Any Schedule for Gnome 41?
We are lots to use it as daily DE
Tks for your work

**Comment by Daivesd** [comment]
Hi ! I'm currently using Fedora 35 with Gnome 41.2, and a workaround to enable the extension on my system was to modify the src/metadata.json file, 'shell-version' section:

    "shell-version": [
        "40",
        "40.1",
        "41",
        "41.2"
    ],

Simply adding the new versions of gnome made it work for me with no evident issues. Still using it to check if everything if fine though. Maybe this helps!

**Comment by ckissane** [comment]
confirmed this works
