### ISSUE TITLE
No application blur at all

### ISSUE THREAD

**Issue by Octodillo** [ckissane/blur-me#55]
On Gnome 41.5 with Blur Me installed from extensions.gnome.org as the only enabled extension and settings below, applications remain entirely opaque. The buttons in the Toggle Application Blur menu do seemingly nothing. Any suggestions on how to get blur in apps?
![Screenshot from 2022-04-05 17-33-54](https://user-images.githubusercontent.com/14184084/161872817-a1509930-dab9-4dd8-90d4-ac05929e8292.png)
(Other extensions were reenabled before taking this screenshot but the settings are unchanged)

**Comment by SadiePi** [comment]
Unchanged on update to Gnome 42

**Comment by Octodillo** [comment]
Aargh, I hate when this happens... I just didn't sufficiently read the readme and just didn't notice this also needs a transparent theme. My bad!
