### ISSUE TITLE
Blur window app (glava) 

### ISSUE THREAD

**Issue by kyokusa** [ckissane/blur-me#6]
Hi ckissane, I wanted to ask you if it was possible to disable some applications perhaps with a specific change, such as conky or glava, thanks
![Schermata del 2021-05-03 15-16-27](https://user-images.githubusercontent.com/17881061/116880654-92ff4300-ac22-11eb-98d1-d576ce0798d3.png)

**Comment by ckissane** [comment]
@kyokusa I will implement this soon!

**Comment by kyokusa** [comment]
> @kyokusa I will implement this soon!

Thanks 👍

**Comment by ckissane** [comment]
@kyokusa as of latest commit you can now toggle blur per process name, it's still pending approval on the extensions site though.

**Comment by kyokusa** [comment]
great job thanks
