### ISSUE TITLE
Error on GNOME 40 // ARCH btw

### ISSUE THREAD

**Issue by lucas2kdk** [ckissane/blur-me#9]
![Screenshot from 2021-05-05 09-49-30](https://user-images.githubusercontent.com/43099632/117111137-7597b980-ad87-11eb-95f9-7a66f4c97742.png)

**Comment by maydayv7** [comment]
Same issue on Solus. It goes off if the `other` option in the Blur section is disabled

**Comment by ckissane** [comment]
For those getting an error on the latest update, a temporary fix is to enable the onscreen keyboard in accessibility settings until the next update that fixes this is approved.

**Comment by ckissane** [comment]
See https://github.com/ckissane/blur-me/issues/10
